stages:
  - Build
  - Test
  - Lint
  - Deploy

Build:
  stage: Build
  image: docker:20.10.24 
  services:
    - docker:20.10.24-dind
  variables:
    DOCKER_HOST: tcp://docker:2375/
    DOCKER_TLS_CERTDIR: ""
  script:
    - docker compose -f docker-compose.yml build

Test:
  stage: Test
  image: node:20-alpine
  script:
    - cd server
    - npm ci
    - npm test
    - cd ../game
    - echo "Teste unitário do filters.threshold como não tem node no client, rodou junto do server!"

Lint:
  stage: Lint
  image: node:20-alpine
  script:
    - cd server
    - npm ci
    - npx eslint .

Deploy:
  stage: Deploy
  image: docker:25
  services:
    - docker:dind
  before_script:
    - echo $CI_JOB_TOKEN | docker login -u $CI_REGISTRY_USER --password-stdin $CI_REGISTRY
  script:
    - docker build -t $CI_REGISTRY_IMAGE/server:latest -f server/Dockerfile.prod server
    - docker build -t $CI_REGISTRY_IMAGE/game:latest -f game/Dockerfile.prod game

    - docker push $CI_REGISTRY_IMAGE/server:latest
    - docker push $CI_REGISTRY_IMAGE/game:latest
  only:
    - main