version: "3.8"

services:
  postgresql:
    image: bitnami/postgresql:latest
    container_name: mkjs_postgresql
    env_file:
      - .env.prod
    volumes:
      - mkjs_pg_data_prod:/bitnami/postgresql
      - ./postgresql/:/docker-entrypoint-initdb.d
    networks:
      - mkjs_network
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U docker -d mkjs" ]
      interval: 5s
      timeout: 3s
      retries: 5
      start_period: 10s

  server:
    build:
      context: ./server
      dockerfile: Dockerfile.prod
    container_name: mkjs_server_prod
    environment:
      - NODE_ENV=production
      - PORT=55555
    depends_on:
      postgresql:
        condition: service_healthy
    networks:
      - mkjs_network

  game:
    build:
      context: ./game
      dockerfile: Dockerfile.prod
    container_name: mkjs_client_prod
    environment:
      - NODE_ENV=production
    networks:
      - mkjs_network

  nginx:
    image: nginx:alpine
    container_name: mkjs_nginx_prod
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/certs:/etc/nginx/certs
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - postgresql
      - server
      - game
    networks:
      - mkjs_network

networks:
  mkjs_network:
    driver: bridge

volumes:
  mkjs_pg_data_prod:
