version: "3.8"

services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile.dev
    container_name: mkjs_server
    ports:
      - "55555:55555"
    volumes:
      - ./server:/usr/src/app/server
    environment:
      - PORT=55555
    command: npx nodemon --watch . --ext js,json server.js

  client:
    build:
      context: ./game
      dockerfile: Dockerfile.dev
    container_name: mkjs_client
    ports:
      - "8080:8080"
    volumes:
      - ./game:/usr/src/app/game
    depends_on:
      - server
