FROM node:20-alpine

WORKDIR /usr/src/app

COPY package*.json ./

RUN npm install

COPY . .

EXPOSE 55555

ENV NODE_ENV=development
ENV PORT=55555

CMD ["npx", "nodemon", "--watch", ".", "--ext", "js,json", "server.js"]
